version: "3.7"
services:
  jupyter:
    image: 'jupyter/datascience-notebook:latest'
    container_name: jupyter
    ports:
      - '8888:8888'
    volumes:
      - jupyter_notebook:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    networks:
      - mynet  

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'test'              # name of database
      MYSQL_USER: 'sample'                # sample is the name of user
      MYSQL_PASSWORD: 'root'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'root'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - mysql-db:/var/lib/mysql
    networks:
      - mynet      

volumes:
  mysql-db:
  jupyter_notebook:
networks:
  mynet: